-- 게시판 마스터 정보 T
INSERT INTO BOARD_MASTER_INFO(BOARD_NAME, BOARD_STATUS) VALUES ('임시1', 'ACTIVE');
INSERT INTO BOARD_MASTER_INFO(BOARD_NAME, BOARD_STATUS) VALUES ('임시1', 'ACTIVE');
INSERT INTO BOARD_MASTER_INFO(BOARD_NAME, BOARD_STATUS) VALUES ('임시2', 'INACTIVE');