-- 게시판 마스터 T
CREATE TABLE BOARD_MASTER_INFO(
    BOARD_MASTER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOARD_NAME VARCHAR(50) NOT NULL,
    BOARD_STATUS VARCHAR(5),
    CREATED_TIME DATETIME NOT NULL,
    UPDATED_TIME DATETIME
);

-- 게시판 게시글 T
CREATE TABLE BOARD_POST(
    BOARD_POST_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOARD_ID BIGINT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    BOARD_CONTENT TEXT NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    POST_STATUS VARCHAR(5) NOT NULL,
    VIEW_COUNT BIGINT NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    UPDATED_TIME DATETIME
);

-- 회원 T
CREATE TABLE MEMBER(
    MEMBER_ID BIGINT PRIMARY KEY AUTO_INCREMNET,
    EMAIL VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    NICKNAME VARCHAR(50) NOT NULL,
    MEMBER_STATUS VARCHAR(5) NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    UPDATED_TIME DATETIMD
);